### ISSUE TITLE
error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 61

### ISSUE THREAD

**Issue by topnoweb** [unclecatvn/IoncubeDecode#1]
hi 
how to fix bug

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 61: Unrecognized content encoding type. libcurl understands deflate, gzip content encodings. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://easytoyou.eu/decoder/ic11php72 in D:\xampp\htdocs\decoder\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:211 Stack trace: #0 D:\xampp\htdocs\decoder\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 D:\xampp\htdocs\decoder\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 D:\xampp\htdocs\decoder\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 in D:\xampp\htdocs\decoder\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 211

**Comment by unclecatvn** [comment]
Hi,
If this code doesn't work, you may have to pay to decode it at the website:
https://easytoyou.eu/decoders, cost about 10-15$, I don't remember clearly.

Vào Th 2, 18 thg 9, 2023 vào lúc 14:36 topnoweb ***@***.***>
đã viết:
